version: "2"

language: java

jdk:
  - oraclejdk8

sudo: required

services:
  - docker

before_install:
  - cd docker
  - docker-compose up -d
  - docker ps -a

before_script:
  - cd ..

script:
  - mvn test